//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchronicWorldService.Utils {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SWResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SWResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SynchronicWorldService.Utils.SWResources", typeof(SWResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} event(s) with Closed status have been removed.
        /// </summary>
        public static string Closed_Events_Removed {
            get {
                return ResourceManager.GetString("Closed_Events_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} contributions have been removed.
        /// </summary>
        public static string DeleteAllPersonContributionsForOpenEvents_Success {
            get {
                return ResourceManager.GetString("DeleteAllPersonContributionsForOpenEvents_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No event found.
        /// </summary>
        public static string Event_Not_Found {
            get {
                return ResourceManager.GetString("Event_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No event Status found.
        /// </summary>
        public static string Event_Status_Not_Found {
            get {
                return ResourceManager.GetString("Event_Status_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No event Type found.
        /// </summary>
        public static string Event_Type_Not_Found {
            get {
                return ResourceManager.GetString("Event_Type_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No person found.
        /// </summary>
        public static string Person_Not_Found {
            get {
                return ResourceManager.GetString("Person_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A service error occured. If the problem persists please contact the administrator.
        /// </summary>
        public static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event is not open.
        /// </summary>
        public static string SuscribeUserToAnEvent_EventNotOpen {
            get {
                return ResourceManager.GetString("SuscribeUserToAnEvent_EventNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User already suscribed to this event.
        /// </summary>
        public static string SuscribeUserToAnEvent_UserAlreadySuscribed {
            get {
                return ResourceManager.GetString("SuscribeUserToAnEvent_UserAlreadySuscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} event(s) have been upgraded from pending status to open status.
        /// </summary>
        public static string Upgrade_Events_Status_From_Pending_To_Open_Done {
            get {
                return ResourceManager.GetString("Upgrade_Events_Status_From_Pending_To_Open_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured when the system trying to upgrade event status from pending to open..
        /// </summary>
        public static string Upgrade_Events_Status_From_Pending_To_Open_Error {
            get {
                return ResourceManager.GetString("Upgrade_Events_Status_From_Pending_To_Open_Error", resourceCulture);
            }
        }
    }
}
