//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchronicWorldConsole.SynchronicWorldService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.EventStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.EventType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.EventStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.EventType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventStatus", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class EventStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventType", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class EventType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfEventHgDy9SCH", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfEventHgDy9SCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Event ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Event Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class Report : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ErrorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ExceptionListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> InfoListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> WarningListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ExceptionList {
            get {
                return this.ExceptionListField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionListField, value) != true)) {
                    this.ExceptionListField = value;
                    this.RaisePropertyChanged("ExceptionList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> InfoList {
            get {
                return this.InfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoListField, value) != true)) {
                    this.InfoListField = value;
                    this.RaisePropertyChanged("InfoList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> WarningList {
            get {
                return this.WarningListField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningListField, value) != true)) {
                    this.WarningListField = value;
                    this.RaisePropertyChanged("WarningList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfArrayOfEventHgDy9SCH", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfArrayOfEventHgDy9SCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronicWorldConsole.SynchronicWorldService.Event> ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronicWorldConsole.SynchronicWorldService.Event> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfboolean", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfPersonHgDy9SCH", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfPersonHgDy9SCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Person ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Person Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfArrayOfEventStatusHgDy9SCH", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfArrayOfEventStatusHgDy9SCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronicWorldConsole.SynchronicWorldService.EventStatus> ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronicWorldConsole.SynchronicWorldService.EventStatus> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfEventStatusHgDy9SCH", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfEventStatusHgDy9SCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.EventStatus ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.EventStatus Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfArrayOfEventTypeHgDy9SCH", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfArrayOfEventTypeHgDy9SCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronicWorldConsole.SynchronicWorldService.EventType> ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronicWorldConsole.SynchronicWorldService.EventType> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfEventTypeHgDy9SCH", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfEventTypeHgDy9SCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.EventType ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.EventType Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfArrayOfContributionHgDy9SCH", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfArrayOfContributionHgDy9SCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronicWorldConsole.SynchronicWorldService.Contribution> ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronicWorldConsole.SynchronicWorldService.Contribution> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contribution", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class Contribution : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.ContributionType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FkEvent {
            get {
                return this.FkEventField;
            }
            set {
                if ((this.FkEventField.Equals(value) != true)) {
                    this.FkEventField = value;
                    this.RaisePropertyChanged("FkEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FkPerson {
            get {
                return this.FkPersonField;
            }
            set {
                if ((this.FkPersonField.Equals(value) != true)) {
                    this.FkPersonField = value;
                    this.RaisePropertyChanged("FkPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.ContributionType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContributionType", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ContributionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfstring", Namespace="http://schemas.datacontract.org/2004/07/SynchronicWorldService.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SynchronicWorldConsole.SynchronicWorldService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SynchronicWorldConsole.SynchronicWorldService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SynchronicWorldService.IEventService")]
    public interface IEventService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/CreateEvent", ReplyAction="http://tempuri.org/IEventService/CreateEventResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH CreateEvent(SynchronicWorldConsole.SynchronicWorldService.Event eventt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/CreateEvent", ReplyAction="http://tempuri.org/IEventService/CreateEventResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH> CreateEventAsync(SynchronicWorldConsole.SynchronicWorldService.Event eventt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/GetEvent", ReplyAction="http://tempuri.org/IEventService/GetEventResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH GetEvent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/GetEvent", ReplyAction="http://tempuri.org/IEventService/GetEventResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH> GetEventAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/GetAllEvents", ReplyAction="http://tempuri.org/IEventService/GetAllEventsResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventHgDy9SCH GetAllEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/GetAllEvents", ReplyAction="http://tempuri.org/IEventService/GetAllEventsResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventHgDy9SCH> GetAllEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/UpdateEvent", ReplyAction="http://tempuri.org/IEventService/UpdateEventResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH UpdateEvent(SynchronicWorldConsole.SynchronicWorldService.Event eventt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/UpdateEvent", ReplyAction="http://tempuri.org/IEventService/UpdateEventResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH> UpdateEventAsync(SynchronicWorldConsole.SynchronicWorldService.Event eventt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/DeleteEvent", ReplyAction="http://tempuri.org/IEventService/DeleteEventResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean DeleteEvent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/DeleteEvent", ReplyAction="http://tempuri.org/IEventService/DeleteEventResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean> DeleteEventAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventServiceChannel : SynchronicWorldConsole.SynchronicWorldService.IEventService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventServiceClient : System.ServiceModel.ClientBase<SynchronicWorldConsole.SynchronicWorldService.IEventService>, SynchronicWorldConsole.SynchronicWorldService.IEventService {
        
        public EventServiceClient() {
        }
        
        public EventServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH CreateEvent(SynchronicWorldConsole.SynchronicWorldService.Event eventt) {
            return base.Channel.CreateEvent(eventt);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH> CreateEventAsync(SynchronicWorldConsole.SynchronicWorldService.Event eventt) {
            return base.Channel.CreateEventAsync(eventt);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH GetEvent(int id) {
            return base.Channel.GetEvent(id);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH> GetEventAsync(int id) {
            return base.Channel.GetEventAsync(id);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventHgDy9SCH GetAllEvents() {
            return base.Channel.GetAllEvents();
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventHgDy9SCH> GetAllEventsAsync() {
            return base.Channel.GetAllEventsAsync();
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH UpdateEvent(SynchronicWorldConsole.SynchronicWorldService.Event eventt) {
            return base.Channel.UpdateEvent(eventt);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventHgDy9SCH> UpdateEventAsync(SynchronicWorldConsole.SynchronicWorldService.Event eventt) {
            return base.Channel.UpdateEventAsync(eventt);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean DeleteEvent(int id) {
            return base.Channel.DeleteEvent(id);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean> DeleteEventAsync(int id) {
            return base.Channel.DeleteEventAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SynchronicWorldService.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/CreatePerson", ReplyAction="http://tempuri.org/IPersonService/CreatePersonResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH CreatePerson(SynchronicWorldConsole.SynchronicWorldService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/CreatePerson", ReplyAction="http://tempuri.org/IPersonService/CreatePersonResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH> CreatePersonAsync(SynchronicWorldConsole.SynchronicWorldService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPerson", ReplyAction="http://tempuri.org/IPersonService/GetPersonResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH GetPerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPerson", ReplyAction="http://tempuri.org/IPersonService/GetPersonResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH> GetPersonAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/UpdatePerson", ReplyAction="http://tempuri.org/IPersonService/UpdatePersonResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH UpdatePerson(SynchronicWorldConsole.SynchronicWorldService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/UpdatePerson", ReplyAction="http://tempuri.org/IPersonService/UpdatePersonResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH> UpdatePersonAsync(SynchronicWorldConsole.SynchronicWorldService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/DeletePerson", ReplyAction="http://tempuri.org/IPersonService/DeletePersonResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean DeletePerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/DeletePerson", ReplyAction="http://tempuri.org/IPersonService/DeletePersonResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean> DeletePersonAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : SynchronicWorldConsole.SynchronicWorldService.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<SynchronicWorldConsole.SynchronicWorldService.IPersonService>, SynchronicWorldConsole.SynchronicWorldService.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH CreatePerson(SynchronicWorldConsole.SynchronicWorldService.Person person) {
            return base.Channel.CreatePerson(person);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH> CreatePersonAsync(SynchronicWorldConsole.SynchronicWorldService.Person person) {
            return base.Channel.CreatePersonAsync(person);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH GetPerson(int id) {
            return base.Channel.GetPerson(id);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH> GetPersonAsync(int id) {
            return base.Channel.GetPersonAsync(id);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH UpdatePerson(SynchronicWorldConsole.SynchronicWorldService.Person person) {
            return base.Channel.UpdatePerson(person);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfPersonHgDy9SCH> UpdatePersonAsync(SynchronicWorldConsole.SynchronicWorldService.Person person) {
            return base.Channel.UpdatePersonAsync(person);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean DeletePerson(int id) {
            return base.Channel.DeletePerson(id);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean> DeletePersonAsync(int id) {
            return base.Channel.DeletePersonAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SynchronicWorldService.IEnumsService")]
    public interface IEnumsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnumsService/GetAllEventsStatus", ReplyAction="http://tempuri.org/IEnumsService/GetAllEventsStatusResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventStatusHgDy9SCH GetAllEventsStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnumsService/GetAllEventsStatus", ReplyAction="http://tempuri.org/IEnumsService/GetAllEventsStatusResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventStatusHgDy9SCH> GetAllEventsStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnumsService/FindEventStatusByCode", ReplyAction="http://tempuri.org/IEnumsService/FindEventStatusByCodeResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventStatusHgDy9SCH FindEventStatusByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnumsService/FindEventStatusByCode", ReplyAction="http://tempuri.org/IEnumsService/FindEventStatusByCodeResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventStatusHgDy9SCH> FindEventStatusByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnumsService/GetAllEventsType", ReplyAction="http://tempuri.org/IEnumsService/GetAllEventsTypeResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventTypeHgDy9SCH GetAllEventsType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnumsService/GetAllEventsType", ReplyAction="http://tempuri.org/IEnumsService/GetAllEventsTypeResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventTypeHgDy9SCH> GetAllEventsTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnumsService/FindEventTypeByCode", ReplyAction="http://tempuri.org/IEnumsService/FindEventTypeByCodeResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventTypeHgDy9SCH FindEventTypeByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnumsService/FindEventTypeByCode", ReplyAction="http://tempuri.org/IEnumsService/FindEventTypeByCodeResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventTypeHgDy9SCH> FindEventTypeByCodeAsync(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnumsServiceChannel : SynchronicWorldConsole.SynchronicWorldService.IEnumsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnumsServiceClient : System.ServiceModel.ClientBase<SynchronicWorldConsole.SynchronicWorldService.IEnumsService>, SynchronicWorldConsole.SynchronicWorldService.IEnumsService {
        
        public EnumsServiceClient() {
        }
        
        public EnumsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnumsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnumsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnumsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventStatusHgDy9SCH GetAllEventsStatus() {
            return base.Channel.GetAllEventsStatus();
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventStatusHgDy9SCH> GetAllEventsStatusAsync() {
            return base.Channel.GetAllEventsStatusAsync();
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventStatusHgDy9SCH FindEventStatusByCode(string code) {
            return base.Channel.FindEventStatusByCode(code);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventStatusHgDy9SCH> FindEventStatusByCodeAsync(string code) {
            return base.Channel.FindEventStatusByCodeAsync(code);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventTypeHgDy9SCH GetAllEventsType() {
            return base.Channel.GetAllEventsType();
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfEventTypeHgDy9SCH> GetAllEventsTypeAsync() {
            return base.Channel.GetAllEventsTypeAsync();
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventTypeHgDy9SCH FindEventTypeByCode(string code) {
            return base.Channel.FindEventTypeByCode(code);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfEventTypeHgDy9SCH> FindEventTypeByCodeAsync(string code) {
            return base.Channel.FindEventTypeByCodeAsync(code);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SynchronicWorldService.IContributionService")]
    public interface IContributionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/GetEventContributions", ReplyAction="http://tempuri.org/IContributionService/GetEventContributionsResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfContributionHgDy9SCH GetEventContributions(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/GetEventContributions", ReplyAction="http://tempuri.org/IContributionService/GetEventContributionsResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfContributionHgDy9SCH> GetEventContributionsAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/GetPersonContributions", ReplyAction="http://tempuri.org/IContributionService/GetPersonContributionsResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfContributionHgDy9SCH GetPersonContributions(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/GetPersonContributions", ReplyAction="http://tempuri.org/IContributionService/GetPersonContributionsResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfContributionHgDy9SCH> GetPersonContributionsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/DeleteAllPersonContributionsForOpenEvents" +
            "", ReplyAction="http://tempuri.org/IContributionService/DeleteAllPersonContributionsForOpenEvents" +
            "Response")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean DeleteAllPersonContributionsForOpenEvents(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/DeleteAllPersonContributionsForOpenEvents" +
            "", ReplyAction="http://tempuri.org/IContributionService/DeleteAllPersonContributionsForOpenEvents" +
            "Response")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean> DeleteAllPersonContributionsForOpenEventsAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContributionServiceChannel : SynchronicWorldConsole.SynchronicWorldService.IContributionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContributionServiceClient : System.ServiceModel.ClientBase<SynchronicWorldConsole.SynchronicWorldService.IContributionService>, SynchronicWorldConsole.SynchronicWorldService.IContributionService {
        
        public ContributionServiceClient() {
        }
        
        public ContributionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContributionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContributionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContributionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfContributionHgDy9SCH GetEventContributions(int eventId) {
            return base.Channel.GetEventContributions(eventId);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfContributionHgDy9SCH> GetEventContributionsAsync(int eventId) {
            return base.Channel.GetEventContributionsAsync(eventId);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfContributionHgDy9SCH GetPersonContributions(int userId) {
            return base.Channel.GetPersonContributions(userId);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfArrayOfContributionHgDy9SCH> GetPersonContributionsAsync(int userId) {
            return base.Channel.GetPersonContributionsAsync(userId);
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean DeleteAllPersonContributionsForOpenEvents(int userId) {
            return base.Channel.DeleteAllPersonContributionsForOpenEvents(userId);
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfboolean> DeleteAllPersonContributionsForOpenEventsAsync(int userId) {
            return base.Channel.DeleteAllPersonContributionsForOpenEventsAsync(userId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SynchronicWorldService.IInfoService")]
    public interface IInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoService/GetDatabaseStatus", ReplyAction="http://tempuri.org/IInfoService/GetDatabaseStatusResponse")]
        SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfstring GetDatabaseStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoService/GetDatabaseStatus", ReplyAction="http://tempuri.org/IInfoService/GetDatabaseStatusResponse")]
        System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfstring> GetDatabaseStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInfoServiceChannel : SynchronicWorldConsole.SynchronicWorldService.IInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfoServiceClient : System.ServiceModel.ClientBase<SynchronicWorldConsole.SynchronicWorldService.IInfoService>, SynchronicWorldConsole.SynchronicWorldService.IInfoService {
        
        public InfoServiceClient() {
        }
        
        public InfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfstring GetDatabaseStatus() {
            return base.Channel.GetDatabaseStatus();
        }
        
        public System.Threading.Tasks.Task<SynchronicWorldConsole.SynchronicWorldService.ServiceResponseOfstring> GetDatabaseStatusAsync() {
            return base.Channel.GetDatabaseStatusAsync();
        }
    }
}
