//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchronicWorldService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribution
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public int Fk_Person { get; set; }
        public int Fk_Type { get; set; }
        public int Fk_Event { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Person Person { get; set; }
        public virtual ContributionType ContributionType { get; set; }
    }
}
