//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchronicWorldService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributionType
    {
        public ContributionType()
        {
            this.Contributions = new HashSet<Contribution>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Contribution> Contributions { get; set; }
    }
}
