//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchronicWorldService.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWContext : DbContext
    {
        public SWContext()
            : base("name=SWContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<Person> People { get; set; }
        public IDbSet<Contribution> Contributions { get; set; }
        public IDbSet<ContributionType> ContributionTypes { get; set; }
        public IDbSet<Event> Events { get; set; }
        public IDbSet<EventStatus> EventStatuses { get; set; }
        public IDbSet<EventType> EventTypes { get; set; }
    
        public void SetModified(object entity)
        {
            Entry(entity).State = EntityState.Modified;
        }
        public void SetAdded(object entity)
        {
            Entry(entity).State = EntityState.Added;
        }
        public void SetDeleted(object entity)
        {
            Entry(entity).State = EntityState.Deleted;
        }
        public void GetId(object entity)
        {
            Entry(entity).GetDatabaseValues();
        }
    }
}
